# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e0024875-92ff-44be-adf2-7e2906bf4d0b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e0024875-92ff-44be-adf2-7e2906bf4d0b".device = "/dev/disk/by-uuid/e0024875-92ff-44be-adf2-7e2906bf4d0b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8E4C-A8CD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-badc0975-bd8f-4323-a781-203aa39328fa"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
